version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs --extras "examples"
    pre_build:
      - find docs/examples -name "*.py" ! -name "script_with_args.py" -exec pyreball {} \;
      - pyreball --page-width=90 docs/examples/script_with_args.py -- --sum 23 25 24

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

formats:
  - pdf
  - epub