version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - find docs/examples -name "*.py" ! -name "script_with_args.py" -exec pyreball {} \;
      - pyreball --page-width=90 docs/examples/script_with_args.py -- --sum 23 25 24

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements_examples.txt
    # Install our python package before building the docs
    - method: pip
      path: .

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

formats:
  - pdf
  - epub