version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - find docs/examples -name "*.py" -exec pyreball {} \;

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

formats:
  - pdf
  - epub