site_name: Pyreball
theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - macros:
      module_name: docs/plugins/main
  - mkdocstrings:
      handlers:
        python:
          paths: [ . ]
          options:
            members_order: alphabetical
            separate_signature: true
            filters: [ "!^_", "!print_html", "__str__", "__call__" ]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Get Started: index.md
  - Usage:
      - Basic Printing: basic_printing.md
      - Text Utils: text_utils.md
      - Tables: tables.md
      - Plotting: plotting.md
      - References: references.md
      - CLI Parameters: cli_parameters.md
      - Config File: config_file.md
  - API Documentation:
      - pyreball.html: api/pyreball_html.md
      - pyreball.text: api/pyreball_text.md